In [1]:
import pandas as pd

In [2]:
employees = pd.read_excel("H+ Sport Employees.xlsx", sheet_name="Employees-Table")

In [3]:
employees

,Employee Name,Building,Department,Status,Hire Date,Month,Years,Benefits,Salary,Job Rating,New Salary,Tax Rate,2.91%
0,"Page, Lisa",West,ADC,Full Time,1999-01-11,Jan,25,DMR,24550,1,NaN,NaN,NaN
1,"Taylor, Hector",West,ADC,Half-Time,2011-02-21,Feb,12,DM,26795,4,NaN,NaN,NaN
2,"Dawson, Jonathan",West,ADC,Contract,2007-03-06,Mar,16,NaN,42540,5,NaN,NaN,NaN
3,"Duran, Brian",Taft,ADC,Hourly,2012-08-30,Aug,11,NaN,35680,2,NaN,NaN,NaN
4,"Weber, Larry",Watson,ADC,Full Time,2007-12-31,Dec,16,M,72830,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,"Olsen, Ewan",North,Research/Development,Contract,2007-02-03,Feb,16,NaN,60760,2,NaN,NaN,NaN
737,"Green, Kim",Watson,Research/Development,Half-Time,2000-02-01,Feb,23,DMR,31250,2,NaN,NaN,NaN
738,"Bradshaw, Sheryl",North,Research/Development,Contract,2008-07-10,Jul,15,NaN,64720,5,NaN,NaN,NaN
739,"Riley, David",Taft,Research/Development,Full Time,2010-07-25,Jul,13,DMR,46680,1,NaN,NaN,NaN
740,"Flynn, Melissa",Watson,Research/Development,Hourly,2010-12-31,Dec,13,NaN,19044,1,NaN,NaN,NaN

In [4]:
employees.columns

Index(['Employee Name', 'Building', 'Department', 'Status', 'Hire Date',
       'Month', 'Years', 'Benefits', 'Salary', 'Job Rating', 'New Salary',
       'Tax Rate', '2.91%'],
      dtype='object')

In [5]:
# declaring a list of columns to remove from the dataframe
columns_to_remove = ['Job Rating', 'New Salary','Tax Rate', '2.91%']

In [6]:
# removing the columns from the dataframe
employees = employees.drop(columns=columns_to_remove)

In [9]:
employees

,Employee Name,Building,Department,Status,Hire Date,Month,Years,Benefits,Salary
0,"Page, Lisa",West,ADC,Full Time,1999-01-11,Jan,25,DMR,24550
1,"Taylor, Hector",West,ADC,Half-Time,2011-02-21,Feb,12,DM,26795
2,"Dawson, Jonathan",West,ADC,Contract,2007-03-06,Mar,16,NaN,42540
3,"Duran, Brian",Taft,ADC,Hourly,2012-08-30,Aug,11,NaN,35680
4,"Weber, Larry",Watson,ADC,Full Time,2007-12-31,Dec,16,M,72830
...,...,...,...,...,...,...,...,...,...
736,"Olsen, Ewan",North,Research/Development,Contract,2007-02-03,Feb,16,NaN,60760
737,"Green, Kim",Watson,Research/Development,Half-Time,2000-02-01,Feb,23,DMR,31250
738,"Bradshaw, Sheryl",North,Research/Development,Contract,2008-07-10,Jul,15,NaN,64720
739,"Riley, David",Taft,Research/Development,Full Time,2010-07-25,Jul,13,DMR,46680
740,"Flynn, Melissa",Watson,Research/Development,Hourly,2010-12-31,Dec,13,NaN,19044

In [10]:
employees.columns

Index(['Employee Name', 'Building', 'Department', 'Status', 'Hire Date',
       'Month', 'Years', 'Benefits', 'Salary'],
      dtype='object')