In [8]:
# Importing pandas library for data manipulation and analysis
import pandas as pd

In [7]:
# Creating a sample dataset of customer purchases
data = {
    "id": [1, 2, 3, 4, 5],
    "product customer purchased": ["Widget A", "Widget B", "Widget A", "Widget C", "Widget B"],
    "Name of customer": ["John Doe", "Jane Smith", "Bob Johnson", "Susan Brown", "Mary Wilson"],
    "address of customer": ["123 Main St", "456 Elm St", "789 Oak St", "234 Pine St", "567 Birch St"],
    "email of customer": ["john.doe@email.com", "", "bob.johnson@email.com", "susan.brown@email.com", "mary.wilson@email.com"],
    "phone number of customer": ["123-456-7890", "987-654-3210", "555-123-7890", "777-888-9999", "111-222-3333"],
    "time of purchase": ["2023-08-10 09:15:00", "2023-08-10 10:30:00", "2023-08-11 14:45:00", "2023-08-11 15:30:00", "2023-08-12 11:20:00"]
}

In [9]:
# Creating a dataframe from the sample dataset
sample_data = pd.DataFrame(data)

In [10]:
# Displaying the sample dataframe
sample_data

,id,product customer purchased,Name of customer,address of customer,email of customer,phone number of customer,time of purchase
0,1,Widget A,John Doe,123 Main St,john.doe@email.com,123-456-7890,2023-08-10 09:15:00
1,2,Widget B,Jane Smith,456 Elm St,,987-654-3210,2023-08-10 10:30:00
2,3,Widget A,Bob Johnson,789 Oak St,bob.johnson@email.com,555-123-7890,2023-08-11 14:45:00
3,4,Widget C,Susan Brown,234 Pine St,susan.brown@email.com,777-888-9999,2023-08-11 15:30:00
4,5,Widget B,Mary Wilson,567 Birch St,mary.wilson@email.com,111-222-3333,2023-08-12 11:20:00

In [11]:
# Displaying the first 5 rows of the sample dataframe
sample_data.head()

,id,product customer purchased,Name of customer,address of customer,email of customer,phone number of customer,time of purchase
0,1,Widget A,John Doe,123 Main St,john.doe@email.com,123-456-7890,2023-08-10 09:15:00
1,2,Widget B,Jane Smith,456 Elm St,,987-654-3210,2023-08-10 10:30:00
2,3,Widget A,Bob Johnson,789 Oak St,bob.johnson@email.com,555-123-7890,2023-08-11 14:45:00
3,4,Widget C,Susan Brown,234 Pine St,susan.brown@email.com,777-888-9999,2023-08-11 15:30:00
4,5,Widget B,Mary Wilson,567 Birch St,mary.wilson@email.com,111-222-3333,2023-08-12 11:20:00

In [12]:
# Displaying the last 5 rows of the sample dataframe
sample_data.tail()

,id,product customer purchased,Name of customer,address of customer,email of customer,phone number of customer,time of purchase
0,1,Widget A,John Doe,123 Main St,john.doe@email.com,123-456-7890,2023-08-10 09:15:00
1,2,Widget B,Jane Smith,456 Elm St,,987-654-3210,2023-08-10 10:30:00
2,3,Widget A,Bob Johnson,789 Oak St,bob.johnson@email.com,555-123-7890,2023-08-11 14:45:00
3,4,Widget C,Susan Brown,234 Pine St,susan.brown@email.com,777-888-9999,2023-08-11 15:30:00
4,5,Widget B,Mary Wilson,567 Birch St,mary.wilson@email.com,111-222-3333,2023-08-12 11:20:00

In [13]:
# Displaying the number of rows and columns in the sample dataframe
sample_data.shape

(5, 7)

In [ ]:
# Displaying the column names of the sample dataframe
# It gives the summary of the dataframe structure, it includes the number of non-null entries, data types of each column, and memory usage.
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          5 non-null      int64
 1   product customer purchased  5 non-null      object
 2   Name of customer            5 non-null      object
 3   address of customer         5 non-null      object
 4   email of customer           5 non-null      object
 5   phone number of customer    5 non-null      object
 6   time of purchase            5 non-null      object
dtypes: int64(1), object(6)
memory usage: 412.0+ bytes

In [16]:
# Checking for duplicate rows in the sample dataframe
# df.duplicated() returns a boolean Series indicating whether each row is a duplicate of a previous row. It helps identify duplicate entries in the dataframe.
sample_data.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool