In [1]:
# Importing pandas library for data manipulation and analysis
import pandas as pd

In [2]:
# Reading a CSV file into a pandas dataframe
sample_data = pd.read_csv("sample_data.csv")

In [3]:
# Displaying the first few rows of the dataframe to understand its structure and contents
sample_data.head()

,Name,Email,Phone,Address,City,Country,Date of Birth,Salary
0,Lisa West,andrew23@example.com,(465)852-8470,Unit 5183 Box 8914\nDPO AP 26775,Perezfort,Honduras,2001-08-05,83302.0
1,Jason Cole,kenneth05@example.net,7783540568,73784 Kenneth Stream Apt. 200\nFitzgeraldshire...,Port Andrea,Bolivia,2012-12-04,31035.0
2,Juan Crosby,zbarnes@example.org,(676)328-6244x05295,"0580 Mary Row\nLake Vanessabury, GA 81529",Johnborough,South Africa,1921-02-02,60226.0
3,April Ball,michaelmckinney@example.com,+1-633-685-4901x2113,"6215 Hensley Pass Apt. 136\nSouth Patricia, MN...",New Eric,Greece,2023-05-08,52502.0
4,Donald Jackson,peterdean@example.com,779-437-7643,"156 Macdonald Alley\nWest Scottmouth, MA 82872",Alyssaborough,Namibia,2019-03-07,38687.0

In [4]:
# Displaying the last 5 rows of the sample dataframe
sample_data.tail()

,Name,Email,Phone,Address,City,Country,Date of Birth,Salary
195,Willie Shelton,jamesdavis@example.net,277-426-9077x821,"2277 Kathryn Cliffs\nDanielshire, VI 89502",East Michael,Mongolia,2017-05-20,59788.0
196,Deborah Nicholson,michelle15@example.net,954-765-9968x1900,"3179 Young Brooks Apt. 868\nScottberg, MI 16700",Port Linda,Senegal,1963-07-25,61230.0
197,Vanessa Wu,reginaldowens@example.com,+1-682-798-1566x9050,"1820 Denise Forks\nEast Katieberg, IL 88289",Cassandraview,Israel,1929-01-18,70482.0
198,Robyn Allen,chad33@example.org,212-239-3934x599,"1162 Kathryn Extensions\nEast Larryfurt, MP 70273",Bruceberg,Iran,1941-05-17,73249.0
199,Scott Stewart,valerie39@example.com,956.897.0540,"228 Adrian Pine\nNorth Sean, IL 20499",Alexandraside,New Zealand,2019-09-30,81174.0

In [5]:
# Displaying the shape of the sample dataframe (number of rows and columns)
sample_data.shape

(200, 8)

In [6]:
# Checking for duplicate rows in the sample dataframe
sample_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Length: 200, dtype: bool

In [7]:
# Filtering the dataframe to show only the duplicate rows
duplicate_rows = sample_data[sample_data.duplicated()]

In [8]:
duplicate_rows

,Name,Email,Phone,Address,City,Country,Date of Birth,Salary
28,Amy Parker,zavalacatherine@example.com,8463043459,78272 Garcia Canyon Suite 357\nPort Debbievill...,Lake Calvinborough,Serbia,2001-02-21,54869.0
29,Carlos Mcneil,hilljoshua@example.com,616-938-0801,"5981 Romero Alley\nPort Meganmouth, MA 18811",Anthonyburgh,Burkina Faso,1927-07-16,82122.0
30,Tammy Murphy,susanfranklin@example.com,879.671.4238x85134,"885 Kelly Club Apt. 350\nNew Alicia, CT 25171",Lake Brittanyburgh,Namibia,1999-09-24,75999.0
31,Brittany Rodriguez,thomasgregory@example.net,597.808.5306x8158,"6650 Chris Radial\nMurphyton, WY 24038",Aaronville,Cambodia,1988-12-15,70911.0
32,Scott Stewart,valerie39@example.com,956.897.0540,"228 Adrian Pine\nNorth Sean, IL 20499",Alexandraside,New Zealand,2019-09-30,81174.0
33,Willie Shelton,jamesdavis@example.net,277-426-9077x821,"2277 Kathryn Cliffs\nDanielshire, VI 89502",East Michael,Mongolia,2017-05-20,59788.0
34,Deborah Nicholson,michelle15@example.net,954-765-9968x1900,"3179 Young Brooks Apt. 868\nScottberg, MI 16700",Port Linda,Senegal,1963-07-25,61230.0
35,Vanessa Wu,reginaldowens@example.com,+1-682-798-1566x9050,"1820 Denise Forks\nEast Katieberg, IL 88289",Cassandraview,Israel,1929-01-18,70482.0
36,Robyn Allen,chad33@example.org,212-239-3934x599,"1162 Kathryn Extensions\nEast Larryfurt, MP 70273",Bruceberg,Iran,1941-05-17,73249.0
73,Amy Parker,zavalacatherine@example.com,8463043459,78272 Garcia Canyon Suite 357\nPort Debbievill...,Lake Calvinborough,Serbia,2001-02-21,54869.0
74,Carlos Mcneil,hilljoshua@example.com,616-938-0801,"5981 Romero Alley\nPort Meganmouth, MA 18811",Anthonyburgh,Burkina Faso,1927-07-16,82122.0
75,Tammy Murphy,susanfranklin@example.com,879.671.4238x85134,"885 Kelly Club Apt. 350\nNew Alicia, CT 25171",Lake Brittanyburgh,Namibia,1999-09-24,75999.0
76,Brittany Rodriguez,thomasgregory@example.net,597.808.5306x8158,"6650 Chris Radial\nMurphyton, WY 24038",Aaronville,Cambodia,1988-12-15,70911.0
77,Scott Stewart,valerie39@example.com,956.897.0540,"228 Adrian Pine\nNorth Sean, IL 20499",Alexandraside,New Zealand,2019-09-30,81174.0
78,Willie Shelton,jamesdavis@example.net,277-426-9077x821,"2277 Kathryn Cliffs\nDanielshire, VI 89502",East Michael,Mongolia,2017-05-20,59788.0
79,Deborah Nicholson,michelle15@example.net,954-765-9968x1900,"3179 Young Brooks Apt. 868\nScottberg, MI 16700",Port Linda,Senegal,1963-07-25,61230.0
80,Vanessa Wu,reginaldowens@example.com,+1-682-798-1566x9050,"1820 Denise Forks\nEast Katieberg, IL 88289",Cassandraview,Israel,1929-01-18,70482.0
111,Amy Parker,zavalacatherine@example.com,8463043459,78272 Garcia Canyon Suite 357\nPort Debbievill...,Lake Calvinborough,Serbia,2001-02-21,54869.0
190,Amy Parker,zavalacatherine@example.com,8463043459,78272 Garcia Canyon Suite 357\nPort Debbievill...,Lake Calvinborough,Serbia,2001-02-21,54869.0
191,Carlos Mcneil,hilljoshua@example.com,616-938-0801,"5981 Romero Alley\nPort Meganmouth, MA 18811",Anthonyburgh,Burkina Faso,1927-07-16,82122.0
192,Tammy Murphy,susanfranklin@example.com,879.671.4238x85134,"885 Kelly Club Apt. 350\nNew Alicia, CT 25171",Lake Brittanyburgh,Namibia,1999-09-24,75999.0
193,Brittany Rodriguez,thomasgregory@example.net,597.808.5306x8158,"6650 Chris Radial\nMurphyton, WY 24038",Aaronville,Cambodia,1988-12-15,70911.0
194,Scott Stewart,valerie39@example.com,956.897.0540,"228 Adrian Pine\nNorth Sean, IL 20499",Alexandraside,New Zealand,2019-09-30,81174.0
195,Willie Shelton,jamesdavis@example.net,277-426-9077x821,"2277 Kathryn Cliffs\nDanielshire, VI 89502",East Michael,Mongolia,2017-05-20,59788.0
196,Deborah Nicholson,michelle15@example.net,954-765-9968x1900,"3179 Young Brooks Apt. 868\nScottberg, MI 16700",Port Linda,Senegal,1963-07-25,61230.0
197,Vanessa Wu,reginaldowens@example.com,+1-682-798-1566x9050,"1820 Denise Forks\nEast Katieberg, IL 88289",Cassandraview,Israel,1929-01-18,70482.0
198,Robyn Allen,chad33@example.org,212-239-3934x599,"1162 Kathryn Extensions\nEast Larryfurt, MP 70273",Bruceberg,Iran,1941-05-17,73249.0
199,Scott Stewart,valerie39@example.com,956.897.0540,"228 Adrian Pine\nNorth Sean, IL 20499",Alexandraside,New Zealand,2019-09-30,81174.0