In [ ]:
# importing the necessary libraries
import pandas as pd # for data manipulation
import sqlalchemy as db # for database connection and operations

In [ ]:
# reading the excel file into a pandas dataframe
customers = pd.read_excel("H+ Sport Customers.xlsx", sheet_name="data")

In [ ]:
# removing duplicate rows from the dataframe
customers.drop_duplicates()

,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,Zipcode
0,100,Carol,Shaw,cshaw0@mlb.com,(206)804-8771,8157 Longview Court,Seattle,WA,98121
1,101,Elizabeth,Carr,ecarr1@oracle.com,(512)187-2507,3934 Petterle Trail,Austin,TX,78732
2,102,Ernest,Ramos,eramos2@plala.or.jp,(816)540-4257,8699 Clarendon Terrace,Kansas City,MO,64199
3,103,Jane,Carter,jcarter3@harvard.edu,(214)839-0542,2830 Novick Lane,Irving,TX,75037
4,104,Martha,Cooper,mcooper4@go.com,(727)235-5696,4537 Hoard Lane,Tampa,FL,33625
...,...,...,...,...,...,...,...,...,...
995,1095,Helen,Castillo,hcastillorn@behance.net,(918)612-1410,218 American Ash Lane,Tulsa,OK,74170
996,1096,Peter,Crawford,pcrawfordro@de.vu,(757)162-1265,0915 Grayhawk Street,Herndon,VA,22070
997,1097,Samuel,Fields,sfieldsrp@reverbnation.com,(304)197-3872,24 Scott Pass,Huntington,WV,25726
998,1098,Michael,Gonzalez,mgonzalezrq@hud.gov,(540)782-9635,48057 Hagan Place,Roanoke,VA,24009
999,1099,Louise,Morrison,lmorrisonrr@nifty.com,(786)955-3070,6 Donald Junction,Miami,FL,33147

In [ ]:
# removing the 'Zipcode' column from the dataframe
customers = customers.drop(columns='Zipcode')

In [ ]:
# displaying the dataframe to verify the changes
customers

,CustomerID,FirstName,LastName,Email,Phone,Address,City,State
0,100,Carol,Shaw,cshaw0@mlb.com,(206)804-8771,8157 Longview Court,Seattle,WA
1,101,Elizabeth,Carr,ecarr1@oracle.com,(512)187-2507,3934 Petterle Trail,Austin,TX
2,102,Ernest,Ramos,eramos2@plala.or.jp,(816)540-4257,8699 Clarendon Terrace,Kansas City,MO
3,103,Jane,Carter,jcarter3@harvard.edu,(214)839-0542,2830 Novick Lane,Irving,TX
4,104,Martha,Cooper,mcooper4@go.com,(727)235-5696,4537 Hoard Lane,Tampa,FL
...,...,...,...,...,...,...,...,...
995,1095,Helen,Castillo,hcastillorn@behance.net,(918)612-1410,218 American Ash Lane,Tulsa,OK
996,1096,Peter,Crawford,pcrawfordro@de.vu,(757)162-1265,0915 Grayhawk Street,Herndon,VA
997,1097,Samuel,Fields,sfieldsrp@reverbnation.com,(304)197-3872,24 Scott Pass,Huntington,WV
998,1098,Michael,Gonzalez,mgonzalezrq@hud.gov,(540)782-9635,48057 Hagan Place,Roanoke,VA
999,1099,Louise,Morrison,lmorrisonrr@nifty.com,(786)955-3070,6 Donald Junction,Miami,FL

In [33]:
# creating a connection to the PostgreSQL database using SQLAlchemy
# using neon.tech as the database provider, and providing the necessary credentials and connection parameters to create our datawarehouse
engine = db.create_engine('postgresql://neondb_owner:npg_yg0pVHBLMQ3G@ep-aged-band-an9m81yf-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require')

In [34]:
# loading the customers dataframe into the PostgreSQL database/ our datawarehouse
customers.to_sql('customers', con=engine, if_exists='replace', index=False)

1000

In [35]:
# verifying that the data has been loaded into the database by checking the shape of the dataframe
customers.shape

(1000, 8)